### ISSUE TITLE
Unable to locate package scx in my Ubuntu 24.04

### ISSUE THREAD

**Issue by Ammyi-lin** [sched-ext/scx#1042]
Hello, I see "Currently, only the 24.04 release is supported." in INSTALL.md.
But after updating to this version,  I still can't install scx.

Does anyone know where the problem is?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```
```
$ uname -r
6.8.0-49-generic
```
```
$ sudo apt install -y linux-generic-wip scx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-generic-wip
E: Unable to locate package scx
```

**Comment by hodgesds** [comment]
You may need to add the [PPA](https://launchpad.net/~arighi/+archive/ubuntu/sched-ext) to your system. There's also some extra [installation instructions](https://github.com/sched-ext/scx/blob/main/INSTALL.md#ubuntu) for Ubuntu.

**Comment by arighi** [comment]
@Ammyi-lin I'm not maintaining the scx package anymore, because it requires an insane amount of work to make everything compliant with the Ubuntu / Launchpad policy.

Right now you can get the scx schedulers either by cloning this repo (and compiling them) or installing them via `cargo install ...`.

I'm also planning to deprecate my ppa, because starting with Ubuntu 25.04 (Plucky) the stock kernel will have all the sched_ext support, so there's no reason to maintain a separate ppa.

I'll send a PR later to update INSTALL.md.
