### ISSUE TITLE
[QUESTION] rustland CPU usage in high load

### ISSUE THREAD

**Issue by JohnRTitor** [sched-ext/scx#227]
During kernel compilation, I opened `btop` to see that rustland is using around 7% CPU.
Is this normal?
I suppose for a job like compiling the scheduler has to constantly allocate and switch jobs in the queue. That could result in high CPU utilization.

Specs:
- AMD Ryzen 5 7600
- CachyOS kernel 6.8.4
- 16 Gigs of RAM

**Comment by arighi** [comment]
It depends how many tasks are running concurrently in your system, rustland tries to dispatch tasks directly on the CPUs if they are available/idle (directly from the BPF code, without triggering the user-space scheduling). Otherwise if all the CPUs are busy (= running a task) the additional tasks will be queued to the user-space scheduler.

So, theoretically, if you run N tasks on N CPUs the user-space scheduler doesn't run at all (and you should see scx_rustland using pretty much 0% CPU).

If the amount of tasks is > than the amount of CPUs, scx_rustland will start to do "something", therefore you should see a % of CPU usage greater than 0%.

In your case I guess you may be running a number of concurrent tasks slightly greater than the amount of CPUs, hence you see a small CPU % used by scx_rustland.

Is this the case?

**Comment by JohnRTitor** [comment]
Yes, that solved my question.

On idle/light load, rustland indeed uses 0% CPU with 80 MB memory.
If I start a CPU hungry task like compiling, userspace scheduler is triggered, leading to 7% of CPU usage.

My CPU has 6 cores and 12 threads.
