### ISSUE TITLE
scx_lavd: victim cpu not work as expected

### ISSUE THREAD

**Issue by archerliew** [sched-ext/scx#835]
In lavd_enqueue, if a not current victim cpu was found, we send a IPI to the target CPU, but not reset the target CPU curr task time slice to 0.
This cause target CPU preempt context switch. But in the dispatch path balance_one(), SCX will bypass the dispatch ops in the following code:
`
        if (prev_on_scx) {
                update_curr_scx(rq);
                if ((prev->scx.flags & SCX_TASK_QUEUED) &&
                    prev->scx.slice && !scx_rq_bypassing(rq)) {
                        rq->scx.flags |= SCX_RQ_BAL_KEEP;
                        goto has_tasks;
                }
        }

`
In the LAVD case, the IPI make the target CPU select prev again.
So I think the expensive IPI preemption in enqueue path is seldom work.

**Comment by multics69** [comment]
Ohhh, that's a very good catch! Thanks @archerliew!

**Comment by multics69** [comment]
After looking at the code more, I think the preemption should happen because
1) The remote CPU is kicked with the SCX_KICK_PREEMPT option. See [here](https://github.com/sched-ext/scx/blob/9d45a359578e8fe40151d6e53d517accb5932bc7/scheds/rust/scx_lavd/src/bpf/preempt.bpf.c#L233). 
2) When the SCX_KICK_PREEMPT option is specified, the kick_one_cpu() function resets the task's time slice to zero. See [here](https://git.kernel.org/pub/scm/linux/kernel/git/tj/sched_ext.git/tree/kernel/sched/ext.c#n5667).

Am I missing something?

**Comment by archerliew** [comment]
You are right. Sorry for my mistake.

**Comment by multics69** [comment]
Phew, no problem. For me, it was a nice chance to double-check if the code was correct. Thank you! @archerliew
